name = "mercer-lab"
compatibility_date = "2024-11-01"
pages_build_output_dir = "./build/client"

[vars]
# Add environment variables here or use Cloudflare dashboard
CONTENTFUL_SPACE_ID = ""
CONTENTFUL_ACCESS_TOKEN = ""
